apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-api
  labels:
    app: events-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-api
      ver: v1.0
  template:
    metadata:
      labels:
        app: events-api
        ver: v1.0
    spec:
      containers:
        - name: events-api
          image: vinishvinuaws/events-api:v1.0
          ports:
            - containerPort: 8082